#
# Copyright 2024 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

jt808-server:
  # false: 不会进行任何自动配置
  enabled: true
  dashboard:
    enabled: true
  builtin-filters:
    # 内置的请求日志 filter(仅仅用于调试)
    request-logger:
      enabled: true
    # 内置的请求解码 filter(如果不启用的话，你需要手动解码请求)
    request-decoder:
      enabled: true
  # 分包请求暂存器
  request-sub-package-storage:
    maximum-size: 1024
    ttl: 45s
  ## 指令服务器
  instruction-server:
    # TCP 服务配置(指令服务器)
    tcp-server:
      # 是否启动 TCP 服务
      enabled: true
      # 绑定所有网卡
      host: 0.0.0.0
      # TCP 服务端口
      port: 7777
      ## 指令报文的最大长度
      ## @see: io.netty.handler.codec.DelimiterBasedFrameDecoder.maxFrameLength
      max-instruction-frame-length: 1024
      ## 指令服务器的会话空闲状态检查器(TCP)
      session-idle-state-checker:
        reader-idle-time: 0s
        writer-idle-time: 0s
        all-idle-time: 20m
      ## 请求处理线程
      loop-resources:
        select-count: 1
        worker-count: 10
        thread-name-prefix: xtream-tcp
        daemon: true
        colocate: true
        prefer-native: true
    # UDP 服务配置(指令服务器)
    udp-server:
      # 是否启动 UDP 服务
      enabled: true
      # 绑定所有网卡
      host: 0.0.0.0
      # UDP 服务端口
      port: 8888
      ## 指令服务器的会话空闲状态检查器(UDP)
      session-idle-state-checker:
        max-idle-time: 20m
        check-interval: 10s
        check-backoff-time: 10s
      ## 请求处理线程
      loop-resources:
        select-count: 1
        worker-count: 10
        thread-name-prefix: xtream-udp
        daemon: true
        colocate: true
        prefer-native: true
  ## 附件服务器
  attachment-server:
    # TCP 服务配置(附件服务器)
    tcp-server:
      enabled: true
      host: 0.0.0.0
      port: 7778
      ## 指令报文的最大长度
      ## @see: io.netty.handler.codec.DelimiterBasedFrameDecoder.maxFrameLength
      max-instruction-frame-length: 1024
      ## 苏标扩展码流消息 0x30316364 的最大长度(66560 = 1024 * 65)
      ## @see io.netty.handler.codec.DelimiterBasedFrameDecoder.maxFrameLength
      max-stream-frame-length: 66560
      ## 附件务器的会话空闲状态检查器(TCP)
      session-idle-state-checker:
        reader-idle-time: 0s
        writer-idle-time: 0s
        all-idle-time: 20m
      ## 请求处理线程
      loop-resources:
        select-count: 1
        worker-count: 10
        thread-name-prefix: xtream-tcp
        daemon: true
        colocate: true
        prefer-native: true
    # UDP 服务配置(附件服务器)
    udp-server:
      enabled: true
      # 绑定所有网卡
      host: 0.0.0.0
      # UDP 服务端口
      port: 8889
      ## 附件服务器的会话空闲状态检查器(UDP)
      session-idle-state-checker:
        max-idle-time: 20m
        check-interval: 10s
        check-backoff-time: 10s
      ## 请求处理线程
      loop-resources:
        select-count: 1
        worker-count: 10
        thread-name-prefix: xtream-udp
        daemon: true
        colocate: true
        prefer-native: true
  ## Reactor 用到的调度器配置
  schedulers:
    ## [非阻塞型]处理器的调度器
    non-blocking-handler:
      type: parallel
      bounded-elastic:
        thread-name-prefix: bounded-elastic
        thread-capacity: 10
        queued-task-capacity: 1024
        reject-blocking-task: true
        daemon: true
        ttl: 1m
      parallel:
        thread-name-prefix: parallel
        parallelism: 10
        daemon: true
        reject-blocking-task: true
      single:
        daemon: true
        reject-blocking-task: true
        thread-name-prefix: single
    ## [阻塞型]处理器的调度器
    blocking-handler:
      type: bounded_elastic
      bounded-elastic:
        thread-name-prefix: blocking-bounded-elastic
        thread-capacity: 10
        queued-task-capacity: 1024
        reject-blocking-task: true
        daemon: true
        ttl: 1m
      parallel:
        thread-name-prefix: blocking-parallel
        parallelism: 10
        daemon: true
        reject-blocking-task: true
      single:
        daemon: true
        reject-blocking-task: true
        thread-name-prefix: blocking-single
    ## [事件发布器]的调度器
    event-publisher:
      type: bounded_elastic
      bounded-elastic:
        thread-name-prefix: event-publisher1
        thread-capacity: 10
        queued-task-capacity: 1024
        reject-blocking-task: true
        daemon: true
        ttl: 1m
      parallel:
        thread-name-prefix: event-publisher1
        parallelism: 10
        daemon: true
        reject-blocking-task: true
      single:
        daemon: true
        reject-blocking-task: true
        thread-name-prefix: event-publisher1
    # 上面 3 个 Scheduler 是必须的
    # 下面 是自定义 Scheduler 的初始化(非必须)
    custom-schedulers: { }
