#
# Copyright 2024 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

demo-app-with-storage:
  minio:
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
  attachment-service:
    bucket-name: jt_attachment
spring:
  application:
    name: jt-808-server-quick-start-with-storage
  r2dbc:
    mybatis:
      routing:
        enabled: true
        definitions:
          - name: trace-log-mysql
            as-default: true
            # r2dbc-url: r2dbc:mysql://[username[:password]@]hostname[:port]/[database][?property1=value1&...]
            r2dbc-url: r2dbc:mysql://localhost:3306/jt_808
            username: root
            password: mysql
            pool:
              max-idle-time: PT5M
              validation-query: SELECT 1
              initial-size: 16
              max-size: 16
              acquire-retry: 3
              validation-depth: REMOTE
              max-create-connection-time: PT10S
          - name: trace-log-postgres
            as-default: false
            r2dbc-url: r2dbc:postgres://localhost:5432/jt_808
            username: jt
            password: postgres
            pool:
              max-idle-time: PT5M
              validation-query: SELECT 1
              initial-size: 16
              max-size: 16
              acquire-retry: 3
              validation-depth: REMOTE
              max-create-connection-time: PT10S
          - name: trace-log-clickhouse
            as-default: false
            r2dbc-url: r2dbc:clickhouse://localhost:8123/jt_808
            username: jt
            password: clickhouse
            pool:
              max-idle-time: PT5M
              validation-query: SELECT 1
              initial-size: 16
              max-size: 16
              acquire-retry: 3
              validation-depth: REMOTE
              max-create-connection-time: PT10S

r2dbc:
  mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

########################################################
### xtream-codec-server-reactive 配置####################
########################################################
jt808-server:
  # false: 不会进行任何自动配置
  enabled: true
  ## 指令服务器
  instruction-server:
    # TCP 服务配置(指令服务器)
    tcp-server:
      # 是否启动 TCP 服务
      enabled: true
      # 绑定所有网卡
      host: 0.0.0.0
      # TCP 服务端口
      port: 3927
    # UDP 服务配置(指令服务器)
    udp-server:
      # 是否启动 UDP 服务
      enabled: true
      # 绑定所有网卡
      host: 0.0.0.0
      # UDP 服务端口
      port: 3721
  ## 附件服务器
  attachment-server:
    # TCP 服务配置(附件服务器)
    tcp-server:
      enabled: true
      # 绑定所有网卡
      host: 0.0.0.0
      # TCP 服务端口
      port: 3824
    # UDP 服务配置(附件服务器)
    udp-server:
      enabled: true
      # 绑定所有网卡
      host: 0.0.0.0
      # UDP 服务端口
      port: 3618

logging:
  level:
    root: info
    io.netty.handler.logging.LoggingHandler: debug
