#
# Copyright (c) 2024 xtream-codec
# xtream-codec is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#          http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.
#

jt808-server:
  # false: 不会进行任何自动配置
  enabled: true
  # 分包请求暂存器
  request-sub-package-storage:
    maximum-size: 1024
    ttl: 45s
  # TCP 服务配置
  tcp-server:
    # 是否启动 TCP 服务
    enabled: true
    # 绑定所有网卡
    host: 0.0.0.0
    # TCP 服务端口
    port: 7777
    loop-resources:
      select-count: 1
      worker-count: 10
      thread-name-prefix: xtream-tcp
      daemon: true
      colocate: true
      prefer-native: true
  # UDP 服务配置
  udp-server:
    # 是否启动 UDP 服务
    enabled: true
    # 绑定所有网卡
    host: 0.0.0.0
    # UDP 服务端口
    port: 8888
    # 一个 UDP 包可能包含多个 JT808 报文
    # 是否启用内置的 UDP 包拆分器
    enable-builtin-multiple-udp-package-splitter: true
    loop-resources:
      select-count: 1
      worker-count: 10
      thread-name-prefix: xtream-udp
      daemon: true
      colocate: true
      prefer-native: true
  handler-schedulers:
    non-blocking-scheduler:
      type: parallel
      bounded-elastic:
        thread-name-prefix: bounded-elastic
        thread-capacity: 10
        queued-task-capacity: 1024
        reject-blocking-task: true
        daemon: true
        ttl: 1m
      parallel:
        thread-name-prefix: parallel
        parallelism: 10
        daemon: true
        reject-blocking-task: true
      single:
        daemon: true
        reject-blocking-task: true
        thread-name-prefix: single
    blocking-scheduler:
      type: bounded_elastic
      bounded-elastic:
        thread-name-prefix: blocking-bounded-elastic
        thread-capacity: 10
        queued-task-capacity: 1024
        reject-blocking-task: true
        daemon: true
        ttl: 1m
      parallel:
        thread-name-prefix: blocking-parallel
        parallelism: 10
        daemon: true
        reject-blocking-task: true
      single:
        daemon: true
        reject-blocking-task: true
        thread-name-prefix: blocking-single
