name: Deploy Docs

on:
  push:
    branches:
      - develop
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'
  ## 手动触发
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: 'docs/pnpm-lock.yaml'

      - name: Install & Build Docs
        run: |
          cd docs
          pnpm install --no-frozen-lockfile
          pnpm run docs:build

      - name: Deploy to Own Remote Server
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          SOURCE: "docs/src/.vuepress/dist/"
          TARGET: ${{ secrets.SERVER_TARGET_PATH }}
          ARGS: "-avzr --delete"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/src/.vuepress/dist

  deploy-to-github-pages:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
